Here We Try To Create a New branch  name Like Test And in this we create one file testchecak.

after create we add some data in that file and  push that file in branch in master after success full run....
